version: '3.7'

# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: False
  AIRFLOW__CORE__LOAD_EXAMPLES: False
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__STORE_DAG_CODE: True
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: True
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: True
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:
  postgres:
    image: postgres:13.10-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/:/var/lib/postgresql/data/

  airflow:
    image: apache/airflow:2.5.3-python3.8
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      <<: *airflow_environment
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
    command:
      - bash
      - -c
      - | # https://yaml-multiline.info/
        airflow db init && 
        airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org;
        airflow webserver &
        airflow scheduler;
